import { TCategoriesMenuItems } from "@/types/categoriesMenu";
import AllCategoriesIcon from "@/ui/icons/mainMenu/allCategoriesIcon";
import ExpressDeliveryIcon from "@/ui/icons/mainMenu/expressDeliveryIcon";
import PickUpIcon from "@/ui/icons/mainMenu/pickUpIcon";

export const categoriesMenu: TCategoriesMenuItems = [
  {
    key: "sve-kategorije",
    href: "/",
    title: "Sve kategorije",
    icon: <AllCategoriesIcon />,
    children: [
      {
        key: "bijela-tehnika",
        href: "/",
        title: "Bijela tehnika",
        icon: <AllCategoriesIcon />,
        children: [
          {
            key: "ves-masine",
            href: "/",
            title: "Ves masine",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "masine-za-sudje",
            href: "/",
            title: "Masine za sudje",
            icon: null,
            children: [
              {
                key: "samostojece-masine-za-sudove",
                href: "/",
                title: "Samostojece masine za sudove",
                icon: null,
                children: [],
              },
              {
                key: "ugradne-masine-za-sudove",
                href: "/",
                title: "Ugradne masine za sudove",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "frizideri",
            href: "/",
            title: "Frizideri",
            icon: null,
            children: [
              {
                key: "samostojeci-frizideri",
                href: "/",
                title: "Samostojeci frizideri",
                icon: null,
                children: [],
              },
              {
                key: "ugradni-frizideri",
                href: "/",
                title: "Ugradni frizideri",
                icon: null,
                children: [],
              },
              {
                key: "frizideri-sa-zamrzivacem",
                href: "/",
                title: "Frizideri sa zamrzivacem",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "sporeti",
            href: "/",
            title: "Sporeti",
            icon: null,
            children: [
              {
                key: "konvencionalni",
                href: "/",
                title: "Konvencionalni",
                icon: null,
                children: [],
              },
              {
                key: "staklo-keramicki",
                href: "/",
                title: "Staklo-keramicki",
                icon: null,
                children: [],
              },
              {
                key: "induktoriski",
                href: "/",
                title: "Induktoriski",
                icon: null,
                children: [],
              },
              {
                key: "kombinovani",
                href: "/",
                title: "Kombinovani",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "rerne",
            href: "/",
            title: "Rerne",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "aspiratori",
            href: "/",
            title: "Aspiratori",
            icon: null,
            children: [
              {
                key: "ugradni-aspiratori",
                href: "/",
                title: "Ugradni aspiratori",
                icon: null,
                children: [],
              },
              {
                key: "samostojeci-aspiratori",
                href: "/",
                title: "Samostojeci aspiratori",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-aspiratore",
                href: "/",
                title: "Oprema za aspiratore",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "ugradni-sporeti",
            href: "/",
            title: "Ugradni sporeti",
            icon: null,
            children: [
              {
                key: "staklo-keramicki",
                href: "/",
                title: "Staklo keramicki",
                icon: null,
                children: [],
              },
              {
                key: "induktoriski",
                href: "/",
                title: "Induktoriski",
                icon: null,
                children: [],
              },
              {
                key: "kombinovani",
                href: "/",
                title: "Kombinovani",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "preciscivaci-vazduha",
            href: "/",
            title: "Preciscivaci vazduha",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "grejna-tijela",
            href: "/",
            title: "Grejna tijela",
            icon: null,
            children: [
              {
                key: "bojleri",
                href: "/",
                title: "Bojleri",
                icon: null,
                children: [],
              },
              {
                key: "zidne-peci",
                href: "/",
                title: "Zidne peci",
                icon: null,
                children: [],
              },
              {
                key: "grijalice-za-kupatila",
                href: "/",
                title: "Grijalice za kupatila",
                icon: null,
                children: [],
              },
              {
                key: "kaloriferi",
                href: "/",
                title: "Kaloriferi",
                icon: null,
                children: [],
              },
              {
                key: "peci-na-drva",
                href: "/",
                title: "Peci na drva",
                icon: null,
                children: [],
              },
            ],
          },
        ],
      },
      {
        key: "tv-audio-video-foto",
        href: "/",
        title: "TV, audio, video, foto",
        icon: <AllCategoriesIcon />,
        children: [
          {
            key: "ves-masine",
            href: "/",
            title: "Ves masine",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "masine-za-sudje",
            href: "/",
            title: "Masine za sudje",
            icon: null,
            children: [],
          },
          {
            key: "frizideri",
            href: "/",
            title: "Frizideri",
            icon: null,
            children: [],
          },
          {
            key: "sporeti",
            href: "/",
            title: "Sporeti",
            icon: null,
            children: [
              {
                key: "konvencionalni",
                href: "/",
                title: "Konvencionalni",
                icon: null,
                children: [],
              },
              {
                key: "staklo-keramicki",
                href: "/",
                title: "Staklo-keramicki",
                icon: null,
                children: [],
              },
              {
                key: "induktoriski",
                href: "/",
                title: "Induktoriski",
                icon: null,
                children: [],
              },
              {
                key: "kombinovani",
                href: "/",
                title: "Kombinovani",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "rerne",
            href: "/",
            title: "Rerne",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "aspiratori",
            href: "/",
            title: "Aspiratori",
            icon: null,
            children: [
              {
                key: "ugradni-aspiratori",
                href: "/",
                title: "Ugradni aspiratori",
                icon: null,
                children: [],
              },
              {
                key: "samostojeci-aspiratori",
                href: "/",
                title: "Samostojeci aspiratori",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-aspiratore",
                href: "/",
                title: "Oprema za aspiratore",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "ugradni-sporeti",
            href: "/",
            title: "Ugradni sporeti",
            icon: null,
            children: [
              {
                key: "staklo-keramicki",
                href: "/",
                title: "Staklo keramicki",
                icon: null,
                children: [],
              },
              {
                key: "induktoriski",
                href: "/",
                title: "Induktoriski",
                icon: null,
                children: [],
              },
              {
                key: "kombinovani",
                href: "/",
                title: "Kombinovani",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "preciscivaci-vazduha",
            href: "/",
            title: "Preciscivaci vazduha",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "grejna-tijela",
            href: "/",
            title: "Grejna tijela",
            icon: null,
            children: [
              {
                key: "bojleri",
                href: "/",
                title: "Bojleri",
                icon: null,
                children: [],
              },
              {
                key: "zidne-peci",
                href: "/",
                title: "Zidne peci",
                icon: null,
                children: [],
              },
              {
                key: "grijalice-za-kupatila",
                href: "/",
                title: "Grijalice za kupatila",
                icon: null,
                children: [],
              },
              {
                key: "kaloriferi",
                href: "/",
                title: "Kaloriferi",
                icon: null,
                children: [],
              },
              {
                key: "peci-na-drva",
                href: "/",
                title: "Peci na drva",
                icon: null,
                children: [],
              },
            ],
          },
        ],
      },
      {
        key: "mali-kucni-aparati",
        href: "/",
        title: "Mali kucni aparati",
        icon: <AllCategoriesIcon />,
        children: [
          {
            key: "ves-masine",
            href: "/",
            title: "Ves masine",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "masine-za-sudje",
            href: "/",
            title: "Masine za sudje",
            icon: null,
            children: [
              {
                key: "samostojece-masine-za-sudove",
                href: "/",
                title: "Samostojece masine za sudove",
                icon: null,
                children: [],
              },
              {
                key: "ugradne-masine-za-sudove",
                href: "/",
                title: "Ugradne masine za sudove",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "sporeti",
            href: "/",
            title: "Sporeti",
            icon: null,
            children: [
              {
                key: "konvencionalni",
                href: "/",
                title: "Konvencionalni",
                icon: null,
                children: [],
              },
              {
                key: "staklo-keramicki",
                href: "/",
                title: "Staklo-keramicki",
                icon: null,
                children: [],
              },
              {
                key: "induktoriski",
                href: "/",
                title: "Induktoriski",
                icon: null,
                children: [],
              },
              {
                key: "kombinovani",
                href: "/",
                title: "Kombinovani",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "rerne",
            href: "/",
            title: "Rerne",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "ugradni-sporeti",
            href: "/",
            title: "Ugradni sporeti",
            icon: null,
            children: [
              {
                key: "staklo-keramicki",
                href: "/",
                title: "Staklo keramicki",
                icon: null,
                children: [],
              },
              {
                key: "induktoriski",
                href: "/",
                title: "Induktoriski",
                icon: null,
                children: [],
              },
              {
                key: "kombinovani",
                href: "/",
                title: "Kombinovani",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "preciscivaci-vazduha",
            href: "/",
            title: "Preciscivaci vazduha",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "grejna-tijela",
            href: "/",
            title: "Grejna tijela",
            icon: null,
            children: [
              {
                key: "bojleri",
                href: "/",
                title: "Bojleri",
                icon: null,
                children: [],
              },
              {
                key: "zidne-peci",
                href: "/",
                title: "Zidne peci",
                icon: null,
                children: [],
              },
              {
                key: "grijalice-za-kupatila",
                href: "/",
                title: "Grijalice za kupatila",
                icon: null,
                children: [],
              },
              {
                key: "kaloriferi",
                href: "/",
                title: "Kaloriferi",
                icon: null,
                children: [],
              },
              {
                key: "peci-na-drva",
                href: "/",
                title: "Peci na drva",
                icon: null,
                children: [],
              },
            ],
          },
        ],
      },
      {
        key: "racunari-i-telefoni",
        href: "/",
        title: "Racunari i telefoni",
        icon: <AllCategoriesIcon />,
        children: [
          {
            key: "ves-masine",
            href: "/",
            title: "Ves masine",
            icon: null,
            children: [],
          },
          {
            key: "masine-za-sudje",
            href: "/",
            title: "Masine za sudje",
            icon: null,
            children: [],
          },
          {
            key: "frizideri",
            href: "/",
            title: "Frizideri",
            icon: null,
            children: [],
          },
          {
            key: "sporeti",
            href: "/",
            title: "Sporeti",
            icon: null,
            children: [],
          },
          {
            key: "rerne",
            href: "/",
            title: "Rerne",
            icon: null,
            children: [],
          },
          {
            key: "aspiratori",
            href: "/",
            title: "Aspiratori",
            icon: null,
            children: [],
          },
          {
            key: "ugradni-sporeti",
            href: "/",
            title: "Ugradni sporeti",
            icon: null,
            children: [],
          },
          {
            key: "preciscivaci-vazduha",
            href: "/",
            title: "Preciscivaci vazduha",
            icon: null,
            children: [],
          },
          {
            key: "grejna-tijela",
            href: "/",
            title: "Grejna tijela",
            icon: null,
            children: [],
          },
        ],
      },
      {
        key: "sve-za-kucu",
        href: "/",
        title: "Sve za kucu",
        icon: <AllCategoriesIcon />,
        children: [],
      },
      {
        key: "basta-i-alati",
        href: "/",
        title: "Basta i alati",
        icon: <AllCategoriesIcon />,
        children: [
          {
            key: "ves-masine",
            href: "/",
            title: "Ves masine",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "masine-za-sudje",
            href: "/",
            title: "Masine za sudje",
            icon: null,
            children: [
              {
                key: "samostojece-masine-za-sudove",
                href: "/",
                title: "Samostojece masine za sudove",
                icon: null,
                children: [],
              },
              {
                key: "ugradne-masine-za-sudove",
                href: "/",
                title: "Ugradne masine za sudove",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "frizideri",
            href: "/",
            title: "Frizideri",
            icon: null,
            children: [
              {
                key: "samostojeci-frizideri",
                href: "/",
                title: "Samostojeci frizideri",
                icon: null,
                children: [],
              },
              {
                key: "ugradni-frizideri",
                href: "/",
                title: "Ugradni frizideri",
                icon: null,
                children: [],
              },
              {
                key: "frizideri-sa-zamrzivacem",
                href: "/",
                title: "Frizideri sa zamrzivacem",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "sporeti",
            href: "/",
            title: "Sporeti",
            icon: null,
            children: [],
          },
          {
            key: "rerne",
            href: "/",
            title: "Rerne",
            icon: null,
            children: [],
          },
          {
            key: "aspiratori",
            href: "/",
            title: "Aspiratori",
            icon: null,
            children: [],
          },
          {
            key: "ugradni-sporeti",
            href: "/",
            title: "Ugradni sporeti",
            icon: null,
            children: [],
          },
          {
            key: "preciscivaci-vazduha",
            href: "/",
            title: "Preciscivaci vazduha",
            icon: null,
            children: [],
          },
          {
            key: "grejna-tijela",
            href: "/",
            title: "Grejna tijela",
            icon: null,
            children: [],
          },
        ],
      },
      {
        key: "auto-moto-oprema",
        href: "/",
        title: "Auto moto oprema",
        icon: <AllCategoriesIcon />,
        children: [
          {
            key: "ves-masine",
            href: "/",
            title: "Ves masine",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "ugradni-sporeti",
            href: "/",
            title: "Ugradni sporeti",
            icon: null,
            children: [
              {
                key: "staklo-keramicki",
                href: "/",
                title: "Staklo keramicki",
                icon: null,
                children: [],
              },
              {
                key: "induktoriski",
                href: "/",
                title: "Induktoriski",
                icon: null,
                children: [],
              },
              {
                key: "kombinovani",
                href: "/",
                title: "Kombinovani",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "preciscivaci-vazduha",
            href: "/",
            title: "Preciscivaci vazduha",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
        ],
      },
      {
        key: "sport-i-putovanja",
        href: "/",
        title: "Sport i putovanja",
        icon: <AllCategoriesIcon />,
        children: [
          {
            key: "ves-masine",
            href: "/",
            title: "Ves masine",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "masine-za-sudje",
            href: "/",
            title: "Masine za sudje",
            icon: null,
            children: [
              {
                key: "samostojece-masine-za-sudove",
                href: "/",
                title: "Samostojece masine za sudove",
                icon: null,
                children: [],
              },
              {
                key: "ugradne-masine-za-sudove",
                href: "/",
                title: "Ugradne masine za sudove",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "frizideri",
            href: "/",
            title: "Frizideri",
            icon: null,
            children: [
              {
                key: "samostojeci-frizideri",
                href: "/",
                title: "Samostojeci frizideri",
                icon: null,
                children: [],
              },
              {
                key: "ugradni-frizideri",
                href: "/",
                title: "Ugradni frizideri",
                icon: null,
                children: [],
              },
              {
                key: "frizideri-sa-zamrzivacem",
                href: "/",
                title: "Frizideri sa zamrzivacem",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "sporeti",
            href: "/",
            title: "Sporeti",
            icon: null,
            children: [
              {
                key: "konvencionalni",
                href: "/",
                title: "Konvencionalni",
                icon: null,
                children: [],
              },
              {
                key: "staklo-keramicki",
                href: "/",
                title: "Staklo-keramicki",
                icon: null,
                children: [],
              },
              {
                key: "induktoriski",
                href: "/",
                title: "Induktoriski",
                icon: null,
                children: [],
              },
              {
                key: "kombinovani",
                href: "/",
                title: "Kombinovani",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "rerne",
            href: "/",
            title: "Rerne",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "aspiratori",
            href: "/",
            title: "Aspiratori",
            icon: null,
            children: [
              {
                key: "ugradni-aspiratori",
                href: "/",
                title: "Ugradni aspiratori",
                icon: null,
                children: [],
              },
              {
                key: "samostojeci-aspiratori",
                href: "/",
                title: "Samostojeci aspiratori",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-aspiratore",
                href: "/",
                title: "Oprema za aspiratore",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "ugradni-sporeti",
            href: "/",
            title: "Ugradni sporeti",
            icon: null,
            children: [
              {
                key: "staklo-keramicki",
                href: "/",
                title: "Staklo keramicki",
                icon: null,
                children: [],
              },
              {
                key: "induktoriski",
                href: "/",
                title: "Induktoriski",
                icon: null,
                children: [],
              },
              {
                key: "kombinovani",
                href: "/",
                title: "Kombinovani",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "preciscivaci-vazduha",
            href: "/",
            title: "Preciscivaci vazduha",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "grejna-tijela",
            href: "/",
            title: "Grejna tijela",
            icon: null,
            children: [
              {
                key: "bojleri",
                href: "/",
                title: "Bojleri",
                icon: null,
                children: [],
              },
              {
                key: "zidne-peci",
                href: "/",
                title: "Zidne peci",
                icon: null,
                children: [],
              },
              {
                key: "grijalice-za-kupatila",
                href: "/",
                title: "Grijalice za kupatila",
                icon: null,
                children: [],
              },
              {
                key: "kaloriferi",
                href: "/",
                title: "Kaloriferi",
                icon: null,
                children: [],
              },
              {
                key: "peci-na-drva",
                href: "/",
                title: "Peci na drva",
                icon: null,
                children: [],
              },
            ],
          },
        ],
      },
      {
        key: "moda",
        href: "/",
        title: "Moda",
        icon: <AllCategoriesIcon />,
        children: [
          {
            key: "ves-masine",
            href: "/",
            title: "Ves masine",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "masine-za-sudje",
            href: "/",
            title: "Masine za sudje",
            icon: null,
            children: [
              {
                key: "samostojece-masine-za-sudove",
                href: "/",
                title: "Samostojece masine za sudove",
                icon: null,
                children: [],
              },
              {
                key: "ugradne-masine-za-sudove",
                href: "/",
                title: "Ugradne masine za sudove",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "frizideri",
            href: "/",
            title: "Frizideri",
            icon: null,
            children: [
              {
                key: "samostojeci-frizideri",
                href: "/",
                title: "Samostojeci frizideri",
                icon: null,
                children: [],
              },
              {
                key: "ugradni-frizideri",
                href: "/",
                title: "Ugradni frizideri",
                icon: null,
                children: [],
              },
              {
                key: "frizideri-sa-zamrzivacem",
                href: "/",
                title: "Frizideri sa zamrzivacem",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "sporeti",
            href: "/",
            title: "Sporeti",
            icon: null,
            children: [
              {
                key: "konvencionalni",
                href: "/",
                title: "Konvencionalni",
                icon: null,
                children: [],
              },
              {
                key: "staklo-keramicki",
                href: "/",
                title: "Staklo-keramicki",
                icon: null,
                children: [],
              },
              {
                key: "induktoriski",
                href: "/",
                title: "Induktoriski",
                icon: null,
                children: [],
              },
              {
                key: "kombinovani",
                href: "/",
                title: "Kombinovani",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "rerne",
            href: "/",
            title: "Rerne",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "aspiratori",
            href: "/",
            title: "Aspiratori",
            icon: null,
            children: [
              {
                key: "ugradni-aspiratori",
                href: "/",
                title: "Ugradni aspiratori",
                icon: null,
                children: [],
              },
              {
                key: "samostojeci-aspiratori",
                href: "/",
                title: "Samostojeci aspiratori",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-aspiratore",
                href: "/",
                title: "Oprema za aspiratore",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "ugradni-sporeti",
            href: "/",
            title: "Ugradni sporeti",
            icon: null,
            children: [
              {
                key: "staklo-keramicki",
                href: "/",
                title: "Staklo keramicki",
                icon: null,
                children: [],
              },
              {
                key: "induktoriski",
                href: "/",
                title: "Induktoriski",
                icon: null,
                children: [],
              },
              {
                key: "kombinovani",
                href: "/",
                title: "Kombinovani",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "preciscivaci-vazduha",
            href: "/",
            title: "Preciscivaci vazduha",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "grejna-tijela",
            href: "/",
            title: "Grejna tijela",
            icon: null,
            children: [
              {
                key: "bojleri",
                href: "/",
                title: "Bojleri",
                icon: null,
                children: [],
              },
              {
                key: "zidne-peci",
                href: "/",
                title: "Zidne peci",
                icon: null,
                children: [],
              },
              {
                key: "grijalice-za-kupatila",
                href: "/",
                title: "Grijalice za kupatila",
                icon: null,
                children: [],
              },
              {
                key: "kaloriferi",
                href: "/",
                title: "Kaloriferi",
                icon: null,
                children: [],
              },
              {
                key: "peci-na-drva",
                href: "/",
                title: "Peci na drva",
                icon: null,
                children: [],
              },
            ],
          },
        ],
      },
      {
        key: "ljepota-i-zdravlje",
        href: "/",
        title: "Ljepota i zdravlje",
        icon: <AllCategoriesIcon />,
        children: [
          {
            key: "ves-masine",
            href: "/",
            title: "Ves masine",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "masine-za-sudje",
            href: "/",
            title: "Masine za sudje",
            icon: null,
            children: [
              {
                key: "samostojece-masine-za-sudove",
                href: "/",
                title: "Samostojece masine za sudove",
                icon: null,
                children: [],
              },
              {
                key: "ugradne-masine-za-sudove",
                href: "/",
                title: "Ugradne masine za sudove",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "frizideri",
            href: "/",
            title: "Frizideri",
            icon: null,
            children: [
              {
                key: "samostojeci-frizideri",
                href: "/",
                title: "Samostojeci frizideri",
                icon: null,
                children: [],
              },
              {
                key: "ugradni-frizideri",
                href: "/",
                title: "Ugradni frizideri",
                icon: null,
                children: [],
              },
              {
                key: "frizideri-sa-zamrzivacem",
                href: "/",
                title: "Frizideri sa zamrzivacem",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "sporeti",
            href: "/",
            title: "Sporeti",
            icon: null,
            children: [
              {
                key: "konvencionalni",
                href: "/",
                title: "Konvencionalni",
                icon: null,
                children: [],
              },
              {
                key: "staklo-keramicki",
                href: "/",
                title: "Staklo-keramicki",
                icon: null,
                children: [],
              },
              {
                key: "induktoriski",
                href: "/",
                title: "Induktoriski",
                icon: null,
                children: [],
              },
              {
                key: "kombinovani",
                href: "/",
                title: "Kombinovani",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "rerne",
            href: "/",
            title: "Rerne",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "aspiratori",
            href: "/",
            title: "Aspiratori",
            icon: null,
            children: [
              {
                key: "ugradni-aspiratori",
                href: "/",
                title: "Ugradni aspiratori",
                icon: null,
                children: [],
              },
              {
                key: "samostojeci-aspiratori",
                href: "/",
                title: "Samostojeci aspiratori",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-aspiratore",
                href: "/",
                title: "Oprema za aspiratore",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "ugradni-sporeti",
            href: "/",
            title: "Ugradni sporeti",
            icon: null,
            children: [
              {
                key: "staklo-keramicki",
                href: "/",
                title: "Staklo keramicki",
                icon: null,
                children: [],
              },
              {
                key: "induktoriski",
                href: "/",
                title: "Induktoriski",
                icon: null,
                children: [],
              },
              {
                key: "kombinovani",
                href: "/",
                title: "Kombinovani",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "preciscivaci-vazduha",
            href: "/",
            title: "Preciscivaci vazduha",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "grejna-tijela",
            href: "/",
            title: "Grejna tijela",
            icon: null,
            children: [
              {
                key: "bojleri",
                href: "/",
                title: "Bojleri",
                icon: null,
                children: [],
              },
              {
                key: "zidne-peci",
                href: "/",
                title: "Zidne peci",
                icon: null,
                children: [],
              },
              {
                key: "grijalice-za-kupatila",
                href: "/",
                title: "Grijalice za kupatila",
                icon: null,
                children: [],
              },
              {
                key: "kaloriferi",
                href: "/",
                title: "Kaloriferi",
                icon: null,
                children: [],
              },
              {
                key: "peci-na-drva",
                href: "/",
                title: "Peci na drva",
                icon: null,
                children: [],
              },
            ],
          },
        ],
      },
      {
        key: "hrana-i-pice",
        href: "/",
        title: "Hrana i pice",
        icon: <AllCategoriesIcon />,
        children: [
          {
            key: "ves-masine",
            href: "/",
            title: "Ves masine",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "masine-za-sudje",
            href: "/",
            title: "Masine za sudje",
            icon: null,
            children: [
              {
                key: "samostojece-masine-za-sudove",
                href: "/",
                title: "Samostojece masine za sudove",
                icon: null,
                children: [],
              },
              {
                key: "ugradne-masine-za-sudove",
                href: "/",
                title: "Ugradne masine za sudove",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "frizideri",
            href: "/",
            title: "Frizideri",
            icon: null,
            children: [
              {
                key: "samostojeci-frizideri",
                href: "/",
                title: "Samostojeci frizideri",
                icon: null,
                children: [],
              },
              {
                key: "ugradni-frizideri",
                href: "/",
                title: "Ugradni frizideri",
                icon: null,
                children: [],
              },
              {
                key: "frizideri-sa-zamrzivacem",
                href: "/",
                title: "Frizideri sa zamrzivacem",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "sporeti",
            href: "/",
            title: "Sporeti",
            icon: null,
            children: [
              {
                key: "konvencionalni",
                href: "/",
                title: "Konvencionalni",
                icon: null,
                children: [],
              },
              {
                key: "staklo-keramicki",
                href: "/",
                title: "Staklo-keramicki",
                icon: null,
                children: [],
              },
              {
                key: "induktoriski",
                href: "/",
                title: "Induktoriski",
                icon: null,
                children: [],
              },
              {
                key: "kombinovani",
                href: "/",
                title: "Kombinovani",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "rerne",
            href: "/",
            title: "Rerne",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "aspiratori",
            href: "/",
            title: "Aspiratori",
            icon: null,
            children: [
              {
                key: "ugradni-aspiratori",
                href: "/",
                title: "Ugradni aspiratori",
                icon: null,
                children: [],
              },
              {
                key: "samostojeci-aspiratori",
                href: "/",
                title: "Samostojeci aspiratori",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-aspiratore",
                href: "/",
                title: "Oprema za aspiratore",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "ugradni-sporeti",
            href: "/",
            title: "Ugradni sporeti",
            icon: null,
            children: [
              {
                key: "staklo-keramicki",
                href: "/",
                title: "Staklo keramicki",
                icon: null,
                children: [],
              },
              {
                key: "induktoriski",
                href: "/",
                title: "Induktoriski",
                icon: null,
                children: [],
              },
              {
                key: "kombinovani",
                href: "/",
                title: "Kombinovani",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "preciscivaci-vazduha",
            href: "/",
            title: "Preciscivaci vazduha",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "grejna-tijela",
            href: "/",
            title: "Grejna tijela",
            icon: null,
            children: [
              {
                key: "bojleri",
                href: "/",
                title: "Bojleri",
                icon: null,
                children: [],
              },
              {
                key: "zidne-peci",
                href: "/",
                title: "Zidne peci",
                icon: null,
                children: [],
              },
              {
                key: "grijalice-za-kupatila",
                href: "/",
                title: "Grijalice za kupatila",
                icon: null,
                children: [],
              },
              {
                key: "kaloriferi",
                href: "/",
                title: "Kaloriferi",
                icon: null,
                children: [],
              },
              {
                key: "peci-na-drva",
                href: "/",
                title: "Peci na drva",
                icon: null,
                children: [],
              },
            ],
          },
        ],
      },
      {
        key: "deciji-i-baby-sektor",
        href: "/",
        title: "Deciji i baby sektor",
        icon: <AllCategoriesIcon />,
        children: [
          {
            key: "ves-masine",
            href: "/",
            title: "Ves masine",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "masine-za-sudje",
            href: "/",
            title: "Masine za sudje",
            icon: null,
            children: [
              {
                key: "samostojece-masine-za-sudove",
                href: "/",
                title: "Samostojece masine za sudove",
                icon: null,
                children: [],
              },
              {
                key: "ugradne-masine-za-sudove",
                href: "/",
                title: "Ugradne masine za sudove",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "frizideri",
            href: "/",
            title: "Frizideri",
            icon: null,
            children: [
              {
                key: "samostojeci-frizideri",
                href: "/",
                title: "Samostojeci frizideri",
                icon: null,
                children: [],
              },
              {
                key: "ugradni-frizideri",
                href: "/",
                title: "Ugradni frizideri",
                icon: null,
                children: [],
              },
              {
                key: "frizideri-sa-zamrzivacem",
                href: "/",
                title: "Frizideri sa zamrzivacem",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "sporeti",
            href: "/",
            title: "Sporeti",
            icon: null,
            children: [
              {
                key: "konvencionalni",
                href: "/",
                title: "Konvencionalni",
                icon: null,
                children: [],
              },
              {
                key: "staklo-keramicki",
                href: "/",
                title: "Staklo-keramicki",
                icon: null,
                children: [],
              },
              {
                key: "induktoriski",
                href: "/",
                title: "Induktoriski",
                icon: null,
                children: [],
              },
              {
                key: "kombinovani",
                href: "/",
                title: "Kombinovani",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "rerne",
            href: "/",
            title: "Rerne",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "aspiratori",
            href: "/",
            title: "Aspiratori",
            icon: null,
            children: [
              {
                key: "ugradni-aspiratori",
                href: "/",
                title: "Ugradni aspiratori",
                icon: null,
                children: [],
              },
              {
                key: "samostojeci-aspiratori",
                href: "/",
                title: "Samostojeci aspiratori",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-aspiratore",
                href: "/",
                title: "Oprema za aspiratore",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "ugradni-sporeti",
            href: "/",
            title: "Ugradni sporeti",
            icon: null,
            children: [
              {
                key: "staklo-keramicki",
                href: "/",
                title: "Staklo keramicki",
                icon: null,
                children: [],
              },
              {
                key: "induktoriski",
                href: "/",
                title: "Induktoriski",
                icon: null,
                children: [],
              },
              {
                key: "kombinovani",
                href: "/",
                title: "Kombinovani",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "preciscivaci-vazduha",
            href: "/",
            title: "Preciscivaci vazduha",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "grejna-tijela",
            href: "/",
            title: "Grejna tijela",
            icon: null,
            children: [
              {
                key: "bojleri",
                href: "/",
                title: "Bojleri",
                icon: null,
                children: [],
              },
              {
                key: "zidne-peci",
                href: "/",
                title: "Zidne peci",
                icon: null,
                children: [],
              },
              {
                key: "grijalice-za-kupatila",
                href: "/",
                title: "Grijalice za kupatila",
                icon: null,
                children: [],
              },
              {
                key: "kaloriferi",
                href: "/",
                title: "Kaloriferi",
                icon: null,
                children: [],
              },
              {
                key: "peci-na-drva",
                href: "/",
                title: "Peci na drva",
                icon: null,
                children: [],
              },
            ],
          },
        ],
      },
      {
        key: "pet-shop",
        href: "/",
        title: "Pet shop",
        icon: <AllCategoriesIcon />,
        children: [
          {
            key: "ves-masine",
            href: "/",
            title: "Ves masine",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "masine-za-sudje",
            href: "/",
            title: "Masine za sudje",
            icon: null,
            children: [
              {
                key: "samostojece-masine-za-sudove",
                href: "/",
                title: "Samostojece masine za sudove",
                icon: null,
                children: [],
              },
              {
                key: "ugradne-masine-za-sudove",
                href: "/",
                title: "Ugradne masine za sudove",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "frizideri",
            href: "/",
            title: "Frizideri",
            icon: null,
            children: [
              {
                key: "samostojeci-frizideri",
                href: "/",
                title: "Samostojeci frizideri",
                icon: null,
                children: [],
              },
              {
                key: "ugradni-frizideri",
                href: "/",
                title: "Ugradni frizideri",
                icon: null,
                children: [],
              },
              {
                key: "frizideri-sa-zamrzivacem",
                href: "/",
                title: "Frizideri sa zamrzivacem",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "sporeti",
            href: "/",
            title: "Sporeti",
            icon: null,
            children: [
              {
                key: "konvencionalni",
                href: "/",
                title: "Konvencionalni",
                icon: null,
                children: [],
              },
              {
                key: "staklo-keramicki",
                href: "/",
                title: "Staklo-keramicki",
                icon: null,
                children: [],
              },
              {
                key: "induktoriski",
                href: "/",
                title: "Induktoriski",
                icon: null,
                children: [],
              },
              {
                key: "kombinovani",
                href: "/",
                title: "Kombinovani",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "rerne",
            href: "/",
            title: "Rerne",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "aspiratori",
            href: "/",
            title: "Aspiratori",
            icon: null,
            children: [
              {
                key: "ugradni-aspiratori",
                href: "/",
                title: "Ugradni aspiratori",
                icon: null,
                children: [],
              },
              {
                key: "samostojeci-aspiratori",
                href: "/",
                title: "Samostojeci aspiratori",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-aspiratore",
                href: "/",
                title: "Oprema za aspiratore",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "ugradni-sporeti",
            href: "/",
            title: "Ugradni sporeti",
            icon: null,
            children: [
              {
                key: "staklo-keramicki",
                href: "/",
                title: "Staklo keramicki",
                icon: null,
                children: [],
              },
              {
                key: "induktoriski",
                href: "/",
                title: "Induktoriski",
                icon: null,
                children: [],
              },
              {
                key: "kombinovani",
                href: "/",
                title: "Kombinovani",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "preciscivaci-vazduha",
            href: "/",
            title: "Preciscivaci vazduha",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "grejna-tijela",
            href: "/",
            title: "Grejna tijela",
            icon: null,
            children: [
              {
                key: "bojleri",
                href: "/",
                title: "Bojleri",
                icon: null,
                children: [],
              },
              {
                key: "zidne-peci",
                href: "/",
                title: "Zidne peci",
                icon: null,
                children: [],
              },
              {
                key: "grijalice-za-kupatila",
                href: "/",
                title: "Grijalice za kupatila",
                icon: null,
                children: [],
              },
              {
                key: "kaloriferi",
                href: "/",
                title: "Kaloriferi",
                icon: null,
                children: [],
              },
              {
                key: "peci-na-drva",
                href: "/",
                title: "Peci na drva",
                icon: null,
                children: [],
              },
            ],
          },
        ],
      },
      {
        key: "ostalo",
        href: "/",
        title: "Ostalo",
        icon: <AllCategoriesIcon />,
        children: [
          {
            key: "ves-masine",
            href: "/",
            title: "Ves masine",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "masine-za-sudje",
            href: "/",
            title: "Masine za sudje",
            icon: null,
            children: [
              {
                key: "samostojece-masine-za-sudove",
                href: "/",
                title: "Samostojece masine za sudove",
                icon: null,
                children: [],
              },
              {
                key: "ugradne-masine-za-sudove",
                href: "/",
                title: "Ugradne masine za sudove",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "frizideri",
            href: "/",
            title: "Frizideri",
            icon: null,
            children: [
              {
                key: "samostojeci-frizideri",
                href: "/",
                title: "Samostojeci frizideri",
                icon: null,
                children: [],
              },
              {
                key: "ugradni-frizideri",
                href: "/",
                title: "Ugradni frizideri",
                icon: null,
                children: [],
              },
              {
                key: "frizideri-sa-zamrzivacem",
                href: "/",
                title: "Frizideri sa zamrzivacem",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "sporeti",
            href: "/",
            title: "Sporeti",
            icon: null,
            children: [
              {
                key: "konvencionalni",
                href: "/",
                title: "Konvencionalni",
                icon: null,
                children: [],
              },
              {
                key: "staklo-keramicki",
                href: "/",
                title: "Staklo-keramicki",
                icon: null,
                children: [],
              },
              {
                key: "induktoriski",
                href: "/",
                title: "Induktoriski",
                icon: null,
                children: [],
              },
              {
                key: "kombinovani",
                href: "/",
                title: "Kombinovani",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "rerne",
            href: "/",
            title: "Rerne",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "aspiratori",
            href: "/",
            title: "Aspiratori",
            icon: null,
            children: [
              {
                key: "ugradni-aspiratori",
                href: "/",
                title: "Ugradni aspiratori",
                icon: null,
                children: [],
              },
              {
                key: "samostojeci-aspiratori",
                href: "/",
                title: "Samostojeci aspiratori",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-aspiratore",
                href: "/",
                title: "Oprema za aspiratore",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "ugradni-sporeti",
            href: "/",
            title: "Ugradni sporeti",
            icon: null,
            children: [
              {
                key: "staklo-keramicki",
                href: "/",
                title: "Staklo keramicki",
                icon: null,
                children: [],
              },
              {
                key: "induktoriski",
                href: "/",
                title: "Induktoriski",
                icon: null,
                children: [],
              },
              {
                key: "kombinovani",
                href: "/",
                title: "Kombinovani",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "preciscivaci-vazduha",
            href: "/",
            title: "Preciscivaci vazduha",
            icon: null,
            children: [
              {
                key: "masine-za-susenje-vesa",
                href: "/",
                title: "Masine za susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-vesa",
                href: "/",
                title: "Masine za pranje vesa",
                icon: null,
                children: [],
              },
              {
                key: "masine-za-pranje-i-susenje-vesa",
                href: "/",
                title: "Masine za pranje i susenje vesa",
                icon: null,
                children: [],
              },
              {
                key: "oprema-za-ves-masine",
                href: "/",
                title: "Oprema za ves masine",
                icon: null,
                children: [],
              },
            ],
          },
          {
            key: "grejna-tijela",
            href: "/",
            title: "Grejna tijela",
            icon: null,
            children: [
              {
                key: "bojleri",
                href: "/",
                title: "Bojleri",
                icon: null,
                children: [],
              },
              {
                key: "zidne-peci",
                href: "/",
                title: "Zidne peci",
                icon: null,
                children: [],
              },
              {
                key: "grijalice-za-kupatila",
                href: "/",
                title: "Grijalice za kupatila",
                icon: null,
                children: [],
              },
              {
                key: "kaloriferi",
                href: "/",
                title: "Kaloriferi",
                icon: null,
                children: [],
              },
              {
                key: "peci-na-drva",
                href: "/",
                title: "Peci na drva",
                icon: null,
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    key: "express-dostava",
    href: "/",
    title: "Express dostava",
    icon: <ExpressDeliveryIcon />,
    children: [],
  },
  {
    key: "punktovi-za-preuzimanje",
    href: "/",
    title: "Punktovi za preuzimanje",
    icon: <PickUpIcon />,
    children: [],
  },
];
