export const testingData = {
  USER: {
    id: 1,
    firstName: "Edina",
    lastName: "Mehmedovic",
    phone: "+38268123456",
    email: "edinam@gmail.com",
    address: "V. Vlahovica",
    city: "Budva",
    municipality: "Budva",
    password: "12345678",
    token: "mocked-jwt-token",
  },
};

export const usersList = [
  {
    id: 1,
    firstName: "Edina",
    lastName: "Mehmedovic",
    phone: "+38268123456",
    email: "edinam@gmail.com",
    address: "V. Vlahovica",
    city: "Budva",
    municipality: "Budva",
    password: "12345678",
    token: "mocked-jwt-token",
  },
];

export const municipalities = [
  { id: 0, name: "Podgorica" },
  { id: 1, name: "Nikšić" },
  { id: 2, name: "Pljevlja" },
  { id: 3, name: "Herceg Novi" },
  { id: 4, name: "Bar" },
  { id: 5, name: "Budva" },
  { id: 6, name: "Bijelo Polje" },
  { id: 7, name: "Cetinje" },
  { id: 8, name: "Kotor" },
  { id: 9, name: "Berane" },
  { id: 10, name: "Ulcinj" },
  { id: 11, name: "Tivat" },
  { id: 12, name: "Rožaje" },
  { id: 13, name: "Dobrota" },
  { id: 14, name: "Danilovgrad" },
  { id: 15, name: "Plav" },
  { id: 16, name: "Burtaiši" },
  { id: 17, name: "Škaljari" },
  { id: 18, name: "Mojkovac" },
  { id: 19, name: "Tuzi" },
  { id: 20, name: "Igalo" },
  { id: 21, name: "Bijela" },
  { id: 22, name: "Žabljak" },
  { id: 23, name: "Ibarac" },
  { id: 24, name: "Golubovci" },
  { id: 25, name: "Resnik" },
  { id: 26, name: "Kolašin" },
  { id: 27, name: "Šušanj" },
  { id: 28, name: "Mojanovići" },
  { id: 29, name: "Nedakusi" },
  { id: 30, name: "Mrčevac" },
  { id: 31, name: "Risan" },
  { id: 32, name: "Ozrinići" },
  { id: 33, name: "Budimlja" },
  { id: 34, name: "Sutomore" },
  { id: 35, name: "Pokrajci" },
  { id: 36, name: "Pešca" },
  { id: 37, name: "Polje" },
  { id: 38, name: "Stari Bar" },
  { id: 39, name: "Donje Luge" },
  { id: 40, name: "Beran Selo" },
  { id: 41, name: "Bjeliši" },
  { id: 42, name: "Spuž" },
  { id: 43, name: "Gusinje" },
  { id: 44, name: "Lješnica" },
  { id: 45, name: "Čeluga" },
  { id: 46, name: "Goričani" },
  { id: 47, name: "Zelenika" },
  { id: 48, name: "Dolac" },
  { id: 49, name: "Petrovac" },
  { id: 50, name: "Podi" },
  { id: 51, name: "Plužine" },
  { id: 52, name: "Mahala" },
  { id: 53, name: "Mataguži" },
  { id: 54, name: "Baošići" },
  { id: 55, name: "Polja" },
  { id: 56, name: "Tomba" },
  { id: 57, name: "Đenovići" },
  { id: 58, name: "Prčanj" },
  { id: 59, name: "Meljine" },
  { id: 60, name: "Andrijevica" },
  { id: 61, name: "Kodre" },
  { id: 62, name: "Buče" },
  { id: 63, name: "Kumbor" },
  { id: 64, name: "Bečići" },
  { id: 65, name: "Smajlagića Polje" },
  { id: 66, name: "Donja Lastva" },
  { id: 67, name: "Židovići" },
  { id: 68, name: "Šavnik" },
  { id: 69, name: "Slatina" },
  { id: 70, name: "Sveti Stefan" },
  { id: 71, name: "Gradac" },
  { id: 72, name: "Virpazar" },
  { id: 73, name: "Perast" },
  { id: 74, name: "Goransko" },
  { id: 75, name: "Bare" },
  { id: 76, name: "Njegovuđa" },
  { id: 77, name: "Rijeka Crnojevića" },
];

export const filters = {
  SUBCATEGORIES: [
    {
      code: 'smartphone',
      label: 'Pametni telefoni'
    },
    {
      code: 'regularphone',
      label: 'Glupi telefoni'
    },
    {
      code: 'action',
      label: 'Na akciji (32)'
    },
  ],
  BRANDS: [
    {
      label: 'Alcatel',
      code: 'alcatel',
      additionalInfo: 14,
    },
    {
      label: 'Apple',
      code: 'apple',
      additionalInfo: 8,
    },
    {
      label: 'Asus',
      code: 'asus',
      additionalInfo: 5,
    },
    {
      label: 'BlackBerry',
      code: 'blackberry',
      additionalInfo: 4,
    },
    {
      label: 'Google',
      code: 'google',
      additionalInfo: 7,
    },
    {
      label: 'Honor',
      code: 'honor',
      additionalInfo: 17,
    },
    {
      label: 'HTC',
      code: 'htc',
      additionalInfo: 8,
    },
    {
      label: 'Huawei',
      code: 'huawei',
      additionalInfo: 12,
    },
    {
      label: 'Lenovo',
      code: 'lenovo',
      additionalInfo: 12,
    },
    {
      label: 'LG',
      code: 'lg',
      additionalInfo: 16,
    },
    {
      label: 'Motorola',
      code: 'motorola',
      additionalInfo: 21,
    },
    {
      label: 'Nokia',
      code: 'nokia',
      additionalInfo: 12,
    },
    {
      label: 'OnePlus',
      code: 'oneplus',
      additionalInfo: 7,
    },
    {
      label: 'Oppo',
      code: 'oppo',
      additionalInfo: 6,
    },
    {
      label: 'Realme',
      code: 'realme',
      additionalInfo: 19,
    },
  ],
  RAM: [
    {
      label: '2GB',
      code: '2gb',
      additionalInfo: 26,
    },
    {
      label: '3GB',
      code: '3gb',
      additionalInfo: 15,
    },
    {
      label: '4GB',
      code: '4gb',
      additionalInfo: 46,
    },
    {
      label: '8GB',
      code: '8gb',
      additionalInfo: 24,
    },
    {
      label: '12GB',
      code: '12gb',
      additionalInfo: 7,
    },
  ],
  MEMORY: [
    {
      label: '32GB',
      code: '32gb',
      additionalInfo: 26,
    },
    {
      label: '64GB',
      code: '64gb',
      additionalInfo: 15,
    },
    {
      label: '128GB',
      code: '128gb',
      additionalInfo: 46,
    },
    {
      label: '256GB',
      code: '256gb',
      additionalInfo: 24,
    },
    {
      label: '512GB',
      code: '512gb',
      additionalInfo: 7,
    },
  ],
  OTHER: [
    {
      label: 'NFC',
      code: 'nfc',
      additionalInfo: 26,
    },
    {
      label: '5G',
      code: '5g',
      additionalInfo: 15,
    },
    {
      label: 'Prikljucak za slusalice',
      code: 'prikljucakzaslusalice',
      additionalInfo: 46,
    },
    {
      label: 'Bezicno punjenje',
      code: 'bezicnopunjenje',
      additionalInfo: 24,
    },
  ],
}
